/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-25 13:41:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.yawlfoundation.yawl.smsModule.SMSSender;
import org.jdom2.JDOMException;
import java.io.IOException;

public final class _005fWelcomeToSMSModule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1462853304000L));
    _jspx_dependants.put("/banner.jsp", Long.valueOf(1462853304000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.yawlfoundation.yawl.smsModule.SMSSender");
    _jspx_imports_classes.add("org.jdom2.JDOMException");
    _jspx_imports_classes.add("java.io.IOException");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Welcome to the SMS Module for YAWL</title>\r\n");
      out.write("        <meta name=\"Pragma\" content=\"no-cache\"/>\r\n");
      out.write("        <meta name=\"Cache-Control\" content=\"no-cache\"/>\r\n");
      out.write("        <meta name=\"Expires\" content=\"0\"/>\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./graphics/common.css\"/>\r\n");
      out.write("        <style type=\"TEXT/CSS\"><!--\r\n");
      out.write("        .leftArea\t{\r\n");
      out.write("            color:DarkGrey;\r\n");
      out.write("            background:#E8E8E8;\r\n");
      out.write("        }\r\n");
      out.write("        body{\r\n");
      out.write("            scrollbar-arrow-color:WHITE;\r\n");
      out.write("            scrollbar-track-color:#D6D6D6;\r\n");
      out.write("            scrollbar-shadow-color:#D6D6D6;\r\n");
      out.write("            scrollbar-face-color:#135184;\r\n");
      out.write("            scrollbar-highlight-color:#D6D6D6;\r\n");
      out.write("            scrollbar-darkshadow-color:#135184;\r\n");
      out.write("            scrollbar-3dlight-color:#135184;\r\n");
      out.write("        }\r\n");
      out.write("        //--></style>\r\n");
      out.write("\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("        <!-- Include YAWL Banner Information -->\r\n");
      out.write("        ");
      out.write('	');
      out.write('	');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" background=\"./graphics/bg01.gif\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("                <!--  width=\"116\" height=\"55\"  -->\r\n");
      out.write("                <td valign=\"top\" width=\"35%\" bgcolor=\"#6699cc\" />\r\n");
      out.write("\r\n");
      out.write("                <!-- height=\"55\"  -->\r\n");
      out.write("                <td align=\"center\" valign=\"bottom\" bgcolor=\"#6699cc\" >\r\n");
      out.write("                    <OBJECT classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\"\r\n");
      out.write("                    codebase=\r\n");
      out.write("                    \"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0\"\r\n");
      out.write("                    WIDTH=\"209\" HEIGHT=\"47\" id=\"yawlSMS\" ALIGN=\"center\">\r\n");
      out.write("                        <PARAM NAME=\"movie\" VALUE=\"./graphics/yawl.swf\" />\r\n");
      out.write("                        <PARAM NAME=\"quality\" VALUE=\"high\" />\r\n");
      out.write("                    </OBJECT>\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<td width=\"30%\" align=\"right\" valign=\"top\" bgcolor=\"#6699cc\" />\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("                <td bgcolor=\"#6699cc\"/>\r\n");
      out.write("\t\t\t\t<td bgcolor=\"#6699cc\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t<img src=\"./graphics/subtext.jpg\"/>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("                <td bgcolor=\"#6699cc\"/>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Start Navigation Banner -->\r\n");
      out.write("\t\t<table width=\"100%\" border=\"0\" bgcolor=\"#ffffff\">\r\n");
      out.write("\t\t\t<tr align=\"center\">\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("                    ");

                        try{
                    
      out.write("\r\n");
      out.write("\t\t            <!--End top level navigation links and search -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

        if(request.getMethod().equals("GET")){
        
      out.write("\r\n");
      out.write("        <img src=\"smsomp.jpg\"/>\r\n");
      out.write("\t\t<h3>Please enter your SMS Account username and password</h3>\r\n");
      out.write("\r\n");
      out.write("        <p>This module can send and receive SMS messages and pass the data\r\n");
      out.write("        into and out of the workflow engine.</p>\r\n");
      out.write("\r\n");
      out.write("        <p>In order to pass the messages\r\n");
      out.write("        onto the mobile network this component relies on a proprietary\r\n");
      out.write("            SMS Gateway style Web service.\r\n");
      out.write("        <br/>i.e. It is currently configured to work with accounts\r\n");
      out.write("            (that you will have to create) with\r\n");
      out.write("        <a href=\"http://www.valuesms.com.au\">valuesms.com.au</a>.\r\n");
      out.write("        </p>\r\n");
      out.write("\r\n");
      out.write("        <p>Once you have established an account it is necessary to configure\r\n");
      out.write("        this component with your account username and password.  This way when\r\n");
      out.write("        the process engine needs to send/receive SMS messages it uses your account\r\n");
      out.write("        information.</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \t\t<center>\r\n");
      out.write("\t\t\t<form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/smsWelcome\">\r\n");
      out.write("\t\t\t\t<table border=\"0\" bgcolor=\"#ddddff\" cellpadding=\"10\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>SMS account username</strong>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" name=\"username\" value=\"\" size=\"20\" maxlength=\"20\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<strong>SMS account password</strong>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"password\" name=\"password\" value=\"\" size=\"10\" maxlength=\"10\" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<table border=\"0\" cellspacing=\"20\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" value=\"    Set SMS Credentials    \" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"reset\" value=\"    Clear    \" />\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t</center>\r\n");
      out.write("        ");


        } else { // request.getMethod().equals(POST)

            String username = request.getParameter("username");
            String password = request.getParameter("password");

            SMSSender _smsController = (SMSSender) application.getAttribute("controller");

            _smsController.setSMSUsernameAndPassword(username, password);

        
      out.write("\r\n");
      out.write("        <h3>Thank you</h3>\r\n");
      out.write("        <p>Your SMS username and password have been stored for future\r\n");
      out.write("        usage.</p>\r\n");
      out.write("\r\n");
      out.write("        ");

        }
        
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br/>\r\n");
      out.write("                <br/>\r\n");
      out.write("                <br/>\r\n");
      out.write("                <hr/>\r\n");
      out.write("                <table>\r\n");
      out.write("                    <tr>\r\n");
      out.write("           \t\t<td>\r\n");
      out.write("                        YAWL is distributed under the\r\n");
      out.write("                        <a href=\"http://www.gnu.org/copyleft/lesser.html\">LGPL</a>.\r\n");
      out.write("           \t\t</td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("        ");

        }catch(Exception e){
    
      out.write("\r\n");
      out.write("      </table>\r\n");
      out.write("    ");

            if(e instanceof IOException){
        
      out.write("\r\n");
      out.write("            <font color=\"red\">\r\n");
      out.write("            <h5>Connection Problem</h5>\r\n");
      out.write("            <p>Error: ");
      out.print( e.getMessage() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("            <p>Check the YAWL installation manual for trouble shooting tips.</p>\r\n");
      out.write("            </font>\r\n");
      out.write("        ");

            } else if (e instanceof JDOMException){
                e.printStackTrace();
        
      out.write("\r\n");
      out.write("            <font color=\"red\">\r\n");
      out.write("            <h5>Data Format Problem</h5>\r\n");
      out.write("            <p>Error: ");
      out.print( e.getMessage() );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("            <p>The worklist application failed receive information in an expected format from\r\n");
      out.write("            the engine.</p>\r\n");
      out.write("            </font>\r\n");
      out.write("        ");

            } else {
        
      out.write("\r\n");
      out.write("            <font color=\"red\"><h5>An exception was generated</h5></font>\r\n");
      out.write("            <p><font color=\"red\">Error: ");
      out.print( e.getMessage() != null ? e.getMessage(): "see log files" );
      out.write("</font></p>\r\n");
      out.write("            ");

                e.printStackTrace();
//                RequestDispatcher rd = application.getRequestDispatcher("/availableWork");
//                rd.forward(request, response);
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

            }
        }
        
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
