/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2017-11-25 14:10:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.yawlfoundation.yawl.mailSender.MailSender;
import java.io.*;
import javax.xml.transform.*;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.output.DOMOutputter;

public final class SetSMTP_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.xml.transform");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.jdom2.Document");
    _jspx_imports_classes.add("javax.xml.transform.dom.DOMSource");
    _jspx_imports_classes.add("org.jdom2.output.DOMOutputter");
    _jspx_imports_classes.add("javax.xml.transform.stream.StreamResult");
    _jspx_imports_classes.add("org.yawlfoundation.yawl.mailSender.MailSender");
    _jspx_imports_classes.add("org.jdom2.Element");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<?xml version=\"1.0\"?>\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\t<meta content=\"no-cache\" http-equiv=\"Pragma\" />\r\n");
      out.write("    <meta content=\"no-cache\" http-equiv=\"Cache-Control\" />\r\n");
      out.write("    <meta content=\"no-store\" http-equiv=\"Cache-Control\" />\r\n");
      out.write("    <meta content=\"max-age=0\" http-equiv=\"Cache-Control\" />\r\n");
      out.write("    <meta content=\"1\" http-equiv=\"Expires\" />\r\n");
      out.write("\t\r\n");
      out.write("\t<title>SMTP Setting :</title>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resourceService/theme/com/sun/rave/web/ui/defaulttheme-gray/javascript/formElements.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"/resourceService/theme/com/sun/rave/web/ui/defaulttheme-gray/css/css_master.css\" />\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("       var sjwuic_ScrollCookie = new sjwuic_ScrollCookie('/dynForm.jsp', '/resourceService/faces/dynForm.jsp'); \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <link id=\"link1\" rel=\"stylesheet\" type=\"text/css\" href=\"/resourceService/resources/stylesheet.css\" />\r\n");
      out.write("    <link id=\"lnkFavIcon\" rel=\"shortcut icon\" type=\"image/x-icon\" href=\"/resourceService/resources/favicon.ico\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"body1\" style=\"-rave-layout: grid\" onload=\"return body1_jsObject.setInitialFocus();\" onunload=\"return body1_jsObject.setScrollPosition();\">\r\n");
      out.write("<center>\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<table cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"height: 69px\" id=\"form1:headtable1\"><tbody><tr><td background=\"./resources/headbgleft.jpg\" height=\"69px\" width=\"40%\" valign=\"bottom\" align=\"left\"><p> \r\n");
      out.write("\t\t\t\t\t\t   <a style=\"font-family:verdana; color: #3277ba\" target=\"_blank\" href=\"http://www.yawlfoundation.org/\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  www.yawlfoundation.org\r\n");
      out.write("\t\t\t</a></p></td><td width=\"409px\" height=\"69px\" align=\"center\"><img src=\"./resources/newYAWL.jpg\" border=\"0\" alt=\"YAWL 2.0\" width=\"409px\" height=\"69px\" id=\"form1:headImage1\"/></td><td background=\"./resources/headbgright.jpg\" height=\"69px\" valign=\"bottom\" align=\"right\" width=\"40%\"><p style=\"font-family:verdana; color: #97cbfd\"><i>Leading the World in Process Innovation</i>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</p></td></tr></tbody></table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"form1:pnlContainer\" style=\"position: relative; height: 10px; top: 0; width: 290px\" style=\"position: relative;-rave-layout: grid; position: relative; height: 10px; top: 0; width: 90px\">\r\n");
      out.write("\t\t<span id=\"form1:txtHeader\" class=\"pageHeading\">Set SMTP</span>\r\n");
      out.write("\t\t<div id=\"form1:compPanel\" class=\"dynformOuterPanel\" style=\"position: absolute; height: 130px; width: 390px\" style=\"position: relative;-rave-layout: grid; position: absolute; height: 170px; width: 290px\">\r\n");
      out.write("\t\t");

			if(request.getMethod().equals("GET")){
        
      out.write("\r\n");
      out.write("\t\t<form method=\"post\" action=\"");
      out.print( request.getContextPath() );
      out.write("/setSMTP\">\r\n");
      out.write("\t    \r\n");
      out.write("\t\t\t<label id=\"form1:lblDocument1\" for=\"form1:txtDocument1\" class=\"dynformLabel LblLev2Txt\" style=\"top:  10px\">SMTP :</label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"SMTP\" class=\"dynformInput TxtFld\" style=\"top: 10px; left: 125px\" value=\"\" size=\"40\" maxlength=\"60\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<label id=\"form1:lblDocument1\" for=\"form1:txtDocument1\" class=\"dynformLabel LblLev2Txt\" style=\"top:  30px\">Port :</label>\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"Port\" class=\"dynformInput TxtFld\" style=\"top: 40px; left: 125px\" value=\"\" size=\"40\" maxlength=\"60\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<input style=\"left: 105px ;top: 73px\" class=\"dynformButton Btn2\" type=\"reset\" value=\"Clear\" />\r\n");
      out.write("\t\t\t<input style=\"left: 205px; top: 73px\" class=\"dynformButton Btn2\" type=\"submit\" value=\"Submit\" />\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\t            \r\n");
      out.write("\t        ");


        } else { 

	        String SMTP = request.getParameter("SMTP");
	        String Port = request.getParameter("Port");
	        Element XMLSMTP = new Element("SMTP");
	    	Element Child = new Element("SMTP_Address");
	    	Child.setText(SMTP);
	    	XMLSMTP.addContent(Child);
	         
	    	Element Child2 = new Element("Port");
	    	Child2.setText(Port);
	    	XMLSMTP.addContent(Child2);
		    File file = new File(getServletContext().getRealPath("/files/"), "SMTP.xml");
	    	
	    	try{ 
			     Document doc = new Document(XMLSMTP);
			     DOMOutputter outputter = new DOMOutputter();
			 	 org.w3c.dom.Document DocToXML = outputter.output(doc);
		    	
			 	 // Prepare the DOM document for writing
		         Source source = new DOMSource(DocToXML);
		         // Prepare the output file
		         Result result = new StreamResult(file);
		         // Write the DOM document to the file
		         Transformer xformer = TransformerFactory.newInstance().newTransformer();
		         xformer.transform(source, result);
		       
	        } catch (TransformerConfigurationException e) {
	        } catch (TransformerException e) {
	    	} catch (Exception e) {    
				e.printStackTrace(); 
			} 
		
   

        
      out.write("\r\n");
      out.write("        <h3>Thank you</h3>\r\n");
      out.write("        <p>Your SMTP is configured.</p>\r\n");
      out.write("\r\n");
      out.write("        ");

        }
        
      out.write("\r\n");
      out.write("\t</center>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
